name: Release Docker Image
on:
  # push:
  #   branches: [ release_docker, dev-build ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
env:
  ORG: teralytic
  TS_VERSION: ${{ github.event.inputs.version || '2.5.0' }}
jobs:

  # Build multi-arch TimescaleDB images for both TSL and OSS code.
  timescaledb:

    name: PG${{ matrix.pg }}${{ matrix.oss }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg: [12]
        oss: [ "" ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Build and push multi-platform Docker image for TimescaleDB
      run: make multi${{ matrix.oss }} ORG=$ORG MY_PG_VERSION=${{ matrix.pg }} TS_VERSION=$TS_VERSION

